Autonmap service interface complete

diff --git a/init/autonmap b/init/autonmap
--- a/init/autonmap
+++ b/init/autonmap
@@ -1,55 +1,51 @@
 #!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides:          nmapper
+# Provides:          autonmap
 # Required-Start:    $local_fs $network
 # Required-Stop:     $local_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Service to auto-launch nmap.
-# Description:       Service to auto-launch nmap. 
-#                    Starts default network and port scans every five minutes.
+# Description:       Service to auto-launch nmap and run a series of scans. 
 ### END INIT INFO
 
 . /lib/lsb/init-functions
 
-# /etc/init.d/nmapper: start and stop the nmapper daemon
-
-# Source config if available.  Sane defaults otherwise.
-[ -e '/etc/nmapper.conf' ] && . /etc/nmapper.conf
+# /etc/init.d/autonmap: start and stop the autonmap daemon
 
 # Process' files
-PREFIX=`date +%y%m%d%H%M`
-PIDFILE='/var/run/nmapper.pid'
-OUTDIR=${OUTDIR:-'/opt/nmapper/reports'}
-
-[ -d $DATA ] || mkdir -p $DATA
-
-# Process' binaries
-NMAP=${NMAPBIN:-`which nmap`}
+# TODO: Accept as args?
+PIDFILE='/var/run/autonmap.pid'
+BIN='autonmap'
+WRAPPER="/opt/autonmap/$BIN"
 
 start() {
-  log_daemon_msg "Starting nmapper daemon in dir $DATA" "nmapper"
-  log_daemon_msg "Actually in dir: $(pwd)"
 
-  TARGET=`ip route | awk '$3 == "$DEVICE" {print $1}'`
+  if [ -x $WRAPPER ]; then
+    log_daemon_msg "autonmap: Starting autonmap daemon using wrapper script $WRAPPER"
+    echo
+  else
+    log_failure_msg "autonmap: $WRAPPER does not exist or is not executable!"
+    exit 1
+  fi
 
   start-stop-daemon --pidfile $PIDFILE -m \
-  -b -d $DATA \
-  --start -x 
+  -b \
+  --start -x $WRAPPER
 
-# TODO: Move execution logic to wrapper script
-#  $NMAP \
-#  -- -$(scan $SCAN) \
-#  -$(output $OUTPUT) $PREFIX \
-#  $TARGET
-
-  log_success_msg "nmapper: started successfully"
-  exit 0
+  pgrep $BIN 2>&1 > /dev/null
+  if [ $? = 0 ]; then
+    log_success_msg "autonmap: started successfully"
+    exit 0
+  else
+    log_failure_msg "autonmap: $WRAPPER appears to have failed to start"
+    exit 2
+  fi
 }
 
 stop() {
-  log_daemon_msg "Stopping nmapper daemon" "nmapper"
+  log_daemon_msg "autonmap: Stopping autonmap daemon" "autonmap"
 
   start-stop-daemon --pidfile $PIDFILE \
   --stop -x $NMAP \
@@ -57,7 +53,7 @@ stop() {
 
   rm -f $PIDFILE
 
-  log_success_msg "nmapper: stopped"
+  log_success_msg "autonmap: stopped"
   exit 0
 }
 
@@ -73,7 +69,7 @@ case "$1" in
     start
     ;;
   status)
-    status_of_proc -p $PIDFILE "$NMAP" nmapper
+    status_of_proc -p $PIDFILE "$WRAPPER" autonmap
     exit $?
     ;;
   *)
